apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-iscsi-targetd-plugin
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: csi-iscsi-targetd-sc
