---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: iscsiplugin-pv
  labels:
    name: data-iscsiplugin
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  csi:
    driver: iscsi.csi.k8s.io
    volumeHandle: iscsi-data-id
    volumeAttributes:
      targetPortal: "192.168.0.107:3260"
      portals: "[]"
      iqn: "iqn.2015-06.com.example.test:target1"
      lun: "0"
      iscsiInterface: "default"
      discovery: "true"
      discoveryCHAPAuth: "true"
      sessionCHAPAuth: "false"
