name: Linux tests
on:
  pull_request: {}
  push: {}

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.x
        uses: actions/setup-go@v3.3.0
        with:
          go-version: ^1.17
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Sanity test
        env:
          GITHUB_ACTIONS: true
        run: |
          export PATH=$PATH:$HOME/.local/bin
          make
          echo "is running in github actions: $GITHUB_ACTIONS"
          make sanity-test

      - name: Verification test
        run: |
          ./hack/verify-all.sh
